### ISSUE TITLE
不支持 CREATE Keyword

### ISSUE THREAD

**Issue by jiangmiaoguan** [paperlion/java-cypher-parser#1]
如 CREATE (:银行 {ID: 1, 名称: 'ABC Bank', 地址: 'New York'})

**Comment by paperlion** [comment]
So surprised that someone actually saw my project!!! Thank you so much. I will check this out

**Comment by jiangmiaoguan** [comment]
Thank you very much. I look forward to your improvements. Besides CREATE, there is also no DELETE. Since parsing CREATE is needed, it was mentioned.

**Comment by paperlion** [comment]
Solved. Some usages also changed. Better check the readme file.
